# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

test:
  stage: test
  script:
   - ls -la ~/.ssh/
   - cat ~/.ssh/known_hosts
   - npm install
   - npm test
   - npm run mpdoc
  # Extract coverage %age from Istanbull
  coverage: '/All\s+files\s+[|]\s+([\d.]+)/'
  artifacts:
    paths:
      - coverage/
      - docs/

# Deploy coverage reports
pages:
  stage: deploy
  script:
    - mv docs/ public/
    - mv coverage/ public/coverage
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
