# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

test:
  stage: test
  script:
   - npm install
   - npm test
  # Extract coverage %age from Istanbull
  coverage: '/All\s+files\s+[|]\s+([\d.]+)/'
  artifacts:
    paths:
      - coverage/

# Deploy coverage reports
pages:
  stage: deploy
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
