# See: https://docs.gitlab.com/ce/ci/yaml/README.html

# Base test job
.tests_base:
  stage: test
  script:
   - npm install
   - npm test
  cache:
    # Per branch/job cache
    key: "${CI_COMMIT_REF_SLUG}_${CI_JOB_NAME}"
    paths:
      - node_modules/

# This guy generates coverage / docs stuff for the below 'pages' task
test-node-8:
  extends: .tests_base
  script:
   - npm install
   - npm test
   - npm run mpdoc
  # Extract coverage %age from Istanbull
  coverage: '/All\s+files\s+[|]\s+([\d.]+)/'
  artifacts:
    paths:
      - coverage/
      - docs/

# Check across multiple node versions
test-node-10:
  extends: .tests_base
  image: node:10
  
test-node-6:
  extends: .tests_base
  image: node:6

# Deploy coverage reports & docs
pages:
  stage: deploy
  script:
    - mv docs/ public/
    - mv coverage/ public/coverage
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
